# The host and port that this server listens on.
listener:
  host: localhost
  port: 2525

# Your domain details
domain:
  # The address to your domains smptd server
  host: example.com # eg: lon106.truehost.cloud
  # The username on the domain
  username: username
  # The password to authenticate on the SMTP server
  password: password